TARGET = Echorec

CPP_SOURCES = echorec.cpp ../hothouse.cpp

C_INCLUDES = -I.. -I../../DaisySP/DaisySP-LGPL/Source

LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR  = ../../DaisySP

SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
